### ISSUE TITLE
App Crashes When Re-Taking Receipt Picture

### ISSUE THREAD

**Issue by jgehrig** [wbaumann/SmartReceiptsLibrary#64] opened 2018-01-26 06:46 UTC
**Repro Steps**
1. Add a new receipt (Import or Picture)
2. Save receipt
3. Tap saved receipt picture
4. Tap 'Retake Photo' and accept a new picture
5. The app crashes.

I am running the latest build from master, free debug. [Call Stack](https://github.com/wbaumann/SmartReceiptsLibrary/files/1666811/callstack.txt)

**Suspected Cause**
The callstack suggests this issue is caused by a de-referenced null object. The culprit appears to be:

https://github.com/wbaumann/SmartReceiptsLibrary/blob/b1489434440910bb8f37c4b7ad7afec67a117d29/app/src/main/java/co/smartreceipts/android/receipts/ReceiptsListFragment.java#L321

It looks like the regression may have been introduced by changeset ab191ef2ccb399eb1b154e12020a7dc5caa573c6

A similar check  was previously present. Maybe it got removed accidentally?

A quick fix would be to guard the object with a null check:
```diff
--- a/app/src/main/java/co/smartreceipts/android/receipts/ReceiptsListFragment.java     Mon Jan 15 13:58:04 2018 -0500
+++ b/app/src/main/java/co/smartreceipts/android/receipts/ReceiptsListFragment.java     Fri Jan 26 01:23:23 2018 -0500
@@ -318,7 +318,9 @@
 })
 .subscribe(locatorResponse -> {
     if (!locatorResponse.getThrowable().isPresent()) {
-        loadingProgress.setVisibility(View.VISIBLE);
+        if (loadingProgress != null) {
+            loadingProgress.setVisibility(View.VISIBLE);
+        }
         activityFileResultImporter.importFile(locatorResponse.getRequestCode(),
                 locatorResponse.getResultCode(), locatorResponse.getUri(), trip);
     } else {
@@@
             Toast.makeText(getActivity(), getFlexString(R.string.FILE_SAVE_ERROR), Toast.LENGTH_SHORT).show();
         }
         highlightedReceipt = null;
-        loadingProgress.setVisibility(View.GONE);
+        if (loadingProgress != null) {
+            loadingProgress.setVisibility(View.GONE);
+        }
         activityFileResultLocator.markThatResultsWereConsumed();
     }
 }));
```

**Comment by wbaumann** [comment] 2018-01-26 18:38
Thank you so much for bringing this to my attention and for including such a complete amount of details. I've gone ahead and included your proposed fix as part of:

#https://github.com/wbaumann/SmartReceiptsLibrary/commit/cf6ba0a312dc11a5fb949eecd935af222ee465cb

So it will be available in the next app release. 

If you're curious, the approximate root cause of this issue is:

* This segment of logic is active for the Android `onCreate` -> `onDestroy` portion of the lifecycle
* The view (ie `loadingProgress`), however, is only non-null for the `onCreateView` -> `onDestroyView` portion of the life-cycle, which exists as a subscope of the `onCreate` -> `onDestroy`
* As a result, there exists a possibility in which this view can be `null` but `onDestroy` has not be called to unsubscribe this block of logic

I generally attempt to place all functional logic in the `onResume` -> `onPause` scope (generally meaning that a particular screen is currently active), since this is the smallest subscope for Android life-cycle. In this instance, however, we can potentially require that the user must grant permissions to import the receipt instance, which requires a higher level scope (ie `onCreate` -> `onDestroy`). So while this null check wouldn't be required for the smaller `onResume` -> `onPause` life-cycle scope, it is required for the larger `onCreate` -> `onDestroy`. 

Not sure if that's well explained or not, but I greatly appreciate you letting me know! And the fix is good now. I'll resolve this formally with the 4.10.x release, since then it'll be available in production. Thanks!

**Comment by wbaumann** [comment] 2018-04-17 17:59
Resolving this now that we're not seeing it in the `4.10.x` release. Thanks again for letting me know about this!

**Closed by wbaumann** 2018-04-17 17:59 UTC
